import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "talentapp:project_verification": "7f0e5c3efb17d336a95124237c8297a820b08ff58acb70fb6fbe4f8cceaaea29a2ca66f0ddad627a70662bca1164ae5bee1fbcfc4e67dc84b46099bca7a339ad",
  },
};

import { StacksProvider } from '@/lib/StacksProvider';
import { Toaster } from 'react-hot-toast';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StacksProvider>
          {children}
          <Toaster position="bottom-right" />
        </StacksProvider>
      </body>
    </html>
  );
}

