[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.mainnet.hiro.so"
deployment_fee_rate = 100

[accounts.deployer]
mnemonic = "*** REPLACE WITH YOUR MAINNET DEPLOYER WALLET MNEMONIC OR USE settings/Mainnet.local.toml ***"
balance = 1_000_000_000_000
